[package]
name = "connectors"
version = "0.1.0"
edition = "2024"

[dependencies]
modules = { path = "../modules" }

anyhow = "1"
tracing = "0.1"
dotenvy = "0.15"
tokio = { version = "1", features = ["full"] }
redis = { version = "1.5.0", features = [
    "connection-manager",
    "tokio-native-tls-comp",
] }
native-tls = { version = "0.2", features = ["vendored"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
