-- Add up migration script here
INSERT INTO positions (experience_id,title,start_date,end_date,description,address,job_position,job_type) VALUES
	 (7,'Web Back Office','2023-03-18','2026-04-10','{"Rewrite from VB Net to ASP .Net Core for back office application","Tuning the database with Stored Procedures as a business layer on the backend","Creating a Full REST API with ASP.Net Core as a link between the backend and the client side","Creating an admin panel display for a back office system using angular js"}','Jakarta Selatan, DKI Jakarta','Fulltime','Hybrid'),
	 (1,'Administration Assistant','2017-01-04','2017-03-20','{"Assist in recording cooperative finances","Counting and identifying counterfeit money entering the cooperative","Assisting the marketing team to use products from the cooperative"}','Pekalongan, Jawa Tengah, Indonesia','Internship','Onsite'),
	 (2,'Artificial Intelligence Gen Y','2021-08-02','2022-01-24','{"Get to know about AI and its types in human life","Creating machine learning based AI using Python and its optimization to create good machine learning models","Conduct clean and case studies by analyzing data using statistics to find ideas and problems that can be solved with AI.","Performing web-based AI deployment with streamlit and flask using Python"}','Jakarta Selatan, DKI Jakarta, Indonesia','Internship','Online'),
	 (3,'Accelerated Machine Learning','2022-02-02','2022-07-28','{"Performing analysis on SQL datasets using Python","Conduct data storytelling to become a use case that can be solved","Creating visualizations with Python and Tablue to visually depict data content","Perform Clean Data to be ready to be used for train machine learning","Train machine learning models using algorithms according to the use cases found."}','Jakarta, DKI Jakarta, Indonesia','Internship','Online'),
	 (4,'IDCamp 2022 Machine Learning','2022-05-05','2022-09-05','{"Creating data visualizations using Python","Learn Python programming language deeper for AI and Machine Learning","Create Machine Learning by exploring various algorithms to find better performance","Studying Deap Learning and Neural Networks in Machine Learning","Creating Reinforcement Learning so that Machine Learning can learn over time."}','Jakarta, DKI Jakarta','Course','Online'),
	 (5,'Data Scientist','2022-09-08','2022-10-25','{"Performing analysis on SQL datasets using Python","Conduct data storytelling to become a use case that can be solved","Creating visualizations with Python and Tablue to visually depict data content","Perform Clean Data to be ready to be used for train machine learning","Train machine learning models using algorithms according to the use cases found."}','Jakarta, DKI Jakarta','Internship','Online'),
	 (6,'Data Scientist','2022-11-02','2022-12-15','{"Get use case from Data CSV dataset","Storytelling data with Python and Clean dataset to ready Train for machine learning","Creating data visualizations using Python","Learn Python programming language deeper for AI and Machine Learning","Create Machine Learning by exploring various algorithms to find better performance","Create Deap Learning and Neural Networks in Machine Learning"}','Jakarta, DKI Jakarta','Internship','Online'),
	 (7,'Web Developer','2022-09-15','2024-03-18','{"Creating an application for RDN registration with ASP .Net Framework MVC and Angular JS","Perform custom styling with CSS according to client requests","Perform data management for SQL Server databases","Creating a web Admin Dashboard application using ReactJS","Conducting mentoring related to React JS to rewrite angular js on the web client side"}','Jakarta Selatan, DKI Jakarta','Fulltime','Hybrid');
