ALTER TABLE skills        ADD COLUMN status SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE positions     ADD COLUMN status SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE portfolio     ADD COLUMN status SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE certifications ADD COLUMN status SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE experience    ADD COLUMN status SMALLINT NOT NULL DEFAULT 0;
